config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

   namespace :api, defaults: {format: :json} do
      namespace :v1 do
         # get 'ciudad/all_last_weather', :as => 'all_last_weather'
         resources :ciudad, only: :create do
            collection do
               get :all_cities
               get :all_last_weather
            end
         end
         resources :historial, only: :create do
            collection do
               get :complete_history
            end
         end 
      end
   end

   resources :historial, only: :index
   resources :ciudad, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ciudad.rb
class Ciudad < ApplicationRecord
   has_many :historials
end

app/models/historial.rb
class Historial < ApplicationRecord
   belongs_to :ciudad
end

app/controllers/api/v1/ciudad_controller.rb
class Api::V1::CiudadController < ApplicationController
   def all_last_weather
      @ciudades=Ciudad.all
   end

   def all_cities
      @ciudades = Ciudad.all
   end

   def create
      @ciudad = Ciudad.new(historial_params)

      if @ciudad.save
          render :status => 200,
            :json => { :success => true,
                      status: :created,
                      :info => "created",
                      :data => { :mod_date => @ciudad.created_at.strftime("%d-%m-%Y %H:%M:%S") } }
       else
          render :status => :unprocessable_entity,
                 :json => { :success => false,
                            :info => resource.errors,
                            :data => {} }
       end

   end

   private
      def historial_params
         params.require(:ciudad).permit(:name, :country_code)
      end
end

app/controllers/api/v1/historial_controller.rb
class Api::V1::HistorialController < ApplicationController
   def create
      @historial = Historial.new(historial_params)

      if @historial.save
          render :status => 200,
            :json => { :success => true,
                      status: :created,
                      :info => "created",
                      :data => { :mod_date => @historial.created_at.strftime("%d-%m-%Y %H:%M:%S") } }
       else
          render :status => :unprocessable_entity,
                 :json => { :success => false,
                            :info => resource.errors,
                            :data => {} }
       end

   end

   def complete_history
      @ciudades=Ciudad.all
   end

   private
      def historial_params
         params.require(:historial).permit(:temperatura, :icon, :desc, :ciudad_id)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ciudad_controller.rb
class CiudadController < ApplicationController
   def index
   end
end

app/controllers/historial_controller.rb
class HistorialController < ApplicationController
   def index
      

   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/ciudad/index.html.erb
<%= react_component('CiudadContainer',{ ciudadesPath: all_cities_api_v1_ciudad_index_path(), createPath: api_v1_ciudad_index_path() }) %>

<!-- <div class="row">
   <div class="col-lg-4"></div>
   <div class="col-lg-4">
      <div class="portlet">
         <div>
            <div class="portlet-body">
               <div class="table-responsive">
                   <table class="table">
                       <thead>
                           <tr>
                               <th>#</th>
                               <th>Ciudad</th>
                               <th>Country Code</th>
                           </tr>
                       </thead>
                       <tbody>
                           <tr>
                               <td>1</td>
                               <td>Velonic Admin v1</td>
                               <td>01/01/2015</td>
                           </tr>                        
                       </tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="col-lg-4"></div>
</div> -->

app/views/historial/index.html.erb
<%= react_component('Historial',{ registrosPath: complete_history_api_v1_historial_index_path() }) %>

app/views/home/index.html.erb
<%= react_component('WeatherContainer',{ ciudadesPath: all_last_weather_api_v1_ciudad_index_path(), updatePath: api_v1_historial_index_path() }) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test4talent</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

   <!-- Google-Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:100,300,400,600,700,900,400italic' rel='stylesheet'>
    <link href='http://fonts.googleapis.com/css?family=Cuprum:400,700' rel='stylesheet' type='text/css'>
  </head>

   <body>
      <div class="wrap"> 
      
         <%= react_component('Header',{ homePath: root_path(), historialPath: historial_index_path(), ciudad_Path: ciudad_index_path() }) %>
         <section class="bg-light section" id="clients">
              <div class="container">
               <div class="row text-center">
                  <div class="col-sm-12">
                    <%= yield %>
                  </div>
               </div> 
              </div>
         </section>

      </div>

      <%= react_component('Footer',{ homePath: root_path(), historialPath: historial_index_path(), ciudad_Path: ciudad_index_path() }) %>
  
  </body>
</html>